log_level: "INFO"

# API Server settings
# The NODE_ID environment variable will determine which node's specific API port to use if defined below.
# API_PORT environment variable can override the port for the current node.
api_server:
  default_host: "127.0.0.1"
  # Per-node API port configuration. Values here are defaults if API_PORT is not set.
  ports:
    node1: 8001
    node2: 8002
    node3: 8003
    node4: 8004
    # Add more nodes as needed

# Raft Consensus Algorithm settings
raft:
  # Election timeouts in milliseconds
  election_timeout_min_ms: 350
  election_timeout_max_ms: 700
  # Heartbeat interval in milliseconds (should be less than election_timeout_min_ms)
  heartbeat_interval_ms: 150
  # Snapshot settings
  snapshot_interval_s: 120 
  snapshot_path_template: "raft_snapshots/snapshot_{node_id}.json" 

  # List of all nodes in the Raft cluster.
  # The NODE_ID environment variable identifies the current node from this list.
  # RPC_PORT environment variable can override the rpc_port for the current node.
  nodes:
    - node_id: "node1"
      rpc_host: "127.0.0.1"
      rpc_port: 5001
    - node_id: "node2"
      rpc_host: "127.0.0.1"
      rpc_port: 5002
    - node_id: "node3"
      rpc_host: "127.0.0.1"
      rpc_port: 5003
    - node_id: "node4"
      rpc_host: "127.0.0.1"
      rpc_port: 5004
    # Add more nodes as needed, ensuring node_id is unique.

